### ISSUE TITLE
python版本3.12以下不兼容f-string中嵌套双引号的问题

### ISSUE THREAD

**Issue by Stephan-Sun** [Tony15246/iqihang-cli#1]
pycharm一打开有七十多个报错

**Comment by Tony15246** [comment]
github issue是用来交流技术和解决问题的地方。如欲解决问题，请附上使用的操作系统，运行代码时的python版本，具体报错的信息等，以协助解决问题。

**Comment by Tony15246** [comment]
> GitHub Community is a professional space and should be treated as such.

GitHub Community是专业技术人员之间交流技术和解决问题的社区，单纯地发表感慨不能解决任何问题。github issue是为了高效解决技术问题而存在的。请认真阅读 github community的code of conduct

如欲解决问题，请附上使用的操作系统，运行代码时的python版本，具体报错的信息等，以协助解决问题。

**Comment by Stephan-Sun** [comment]
SyntaxError: f-string: unmatched '['

    print(f"Index: {index}, Name: {lesson["name"]}, 暂不支持处理直播回放")

**Comment by Tony15246** [comment]
python3.12以下的版本不支持在f-string中嵌套双引号，会导致解释器语法分析失败。我的操作系统是滚动更新的，所以python版本一直是最新的，没有遇到这个兼容性问题。

将f-string内部的双引号都改成单引号即可解决此问题。比如说报错的这句改成下面这样就行。

```
print(f"Index: {index}, Name: {lesson['name']}, 暂不支持处理直播回放")
```

**Comment by Tony15246** [comment]
我待会儿推一个兼容性补丁到主分支

**Comment by Tony15246** [comment]
补丁已更新，克隆最新代码就不会出现f-string的语法错误了

**Comment by Stephan-Sun** [comment]
感谢作者，可以用了，作者好人一生平安

**Comment by Tony15246** [comment]
不用谢(ゝ∀･)
